# Line Follower Logging Configuration - DEBUG MODE
global:
  enable_all: true
  console_output: true
  file_output: false
  unbuffered_output: true

rate_limits:
  high_frequency: 0.5
  medium_frequency: 1.0
  low_frequency: 2.0

components:
  tracker:
    enabled: true
    rate_limit: "medium_frequency"
    levels:
      system_events: true
      line_detection: true
      coordinate_transform: true
      velocity_commands: true
      control_loops: false

  linreg:
    enabled: true
    rate_limit: "high_frequency"
    levels:
      detection_events: true
      processing_details: true
      method_attempts: false
      pixel_analysis: false
      visualization_info: false

  detector:
    enabled: true
    rate_limit: "medium_frequency"
    levels:
      image_info: true
      curve_detection: true
      processing_steps: true

  system:
    enabled: true
    rate_limit: "low_frequency"
    levels:
      startup: true
      errors: true
      warnings: true
      debug: true

formatting:
  timestamp: true
  component_prefix: true
  colorized: true

colors:
  error: "\033[91m"
  warning: "\033[93m"
  info: "\033[92m"
  debug: "\033[94m"
  system: "\033[95m"
  reset: "\033[0m"
